spring:
  application:
    name: catalog

  data:
    elasticsearch:
      repositories:
        enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  elasticsearch:
    uris: ${ELASTIC_URL}
    connection-timeout: 60s
    socket-timeout: 60s

logging:
  level:
    dev.nokk.catalog: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

